# Aktywne okno
client.focused          #9d4edd #2d2d2d #ffffff #9d4edd #9d4edd

# Nieaktywne okno (w tle)
client.unfocused        #1a1a1a #1a1a1a #888888 #1a1a1a #1a1a1a

# Nieaktywne ale ostatnio używane
client.focused_inactive #2d2d2d #2d2d2d #aaaaaa #2d2d2d #2d2d2d

# Pilne powiadomienie
client.urgent           #ff4444 #ff4444 #ffffff #ff4444 #ff4444

# Grubość obrysu
default_border pixel 1

# Brak obrysu na pływających oknach
default_floating_border pixel 1

# Odstępy między oknami
gaps inner 5
gaps outer 0

corner_radius 10
smart_corner_radius enable
blur enable
shadows enable